<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::factory(['short' => 'AD', 'name' => 'ANDORRA', 'code' => '376'])->create();
        Country::factory(['short' => 'AE', 'name' => 'UNITED ARAB EMIRATES', 'code' => '971'])->create();
        Country::factory(['short' => 'AF', 'name' => 'AFGHANISTAN', 'code' => '93'])->create();
        Country::factory(['short' => 'AG', 'name' => 'ANTIGUA AND BARBUDA', 'code' => '1268'])->create();
        Country::factory(['short' => 'AI', 'name' => 'ANGUILLA', 'code' => '1264'])->create();
        Country::factory(['short' => 'AL', 'name' => 'ALBANIA', 'code' => '355'])->create();
        Country::factory(['short' => 'AM', 'name' => 'ARMENIA', 'code' => '374'])->create();
        Country::factory(['short' => 'AN', 'name' => 'NETHERLANDS ANTILLES', 'code' => '599'])->create();
        Country::factory(['short' => 'AO', 'name' => 'ANGOLA', 'code' => '244'])->create();
        Country::factory(['short' => 'AQ', 'name' => 'ANTARCTICA', 'code' => '672'])->create();
        Country::factory(['short' => 'AR', 'name' => 'ARGENTINA', 'code' => '54'])->create();
        Country::factory(['short' => 'AS', 'name' => 'AMERICAN SAMOA', 'code' => '1684'])->create();
        Country::factory(['short' => 'AT', 'name' => 'AUSTRIA', 'code' => '43'])->create();
        Country::factory(['short' => 'AU', 'name' => 'AUSTRALIA', 'code' => '61'])->create();
        Country::factory(['short' => 'AW', 'name' => 'ARUBA', 'code' => '297'])->create();
        Country::factory(['short' => 'AZ', 'name' => 'AZERBAIJAN', 'code' => '994'])->create();
        Country::factory(['short' => 'BA', 'name' => 'BOSNIA AND HERZEGOVINA', 'code' => '387'])->create();
        Country::factory(['short' => 'BB', 'name' => 'BARBADOS', 'code' => '1246'])->create();
        Country::factory(['short' => 'BD', 'name' => 'BANGLADESH', 'code' => '880'])->create();
        Country::factory(['short' => 'BE', 'name' => 'BELGIUM', 'code' => '32'])->create();
        Country::factory(['short' => 'BF', 'name' => 'BURKINA FASO', 'code' => '226'])->create();
        Country::factory(['short' => 'BG', 'name' => 'BULGARIA', 'code' => '359'])->create();
        Country::factory(['short' => 'BH', 'name' => 'BAHRAIN', 'code' => '973'])->create();
        Country::factory(['short' => 'BI', 'name' => 'BURUNDI', 'code' => '257'])->create();
        Country::factory(['short' => 'BJ', 'name' => 'BENIN', 'code' => '229'])->create();
        Country::factory(['short' => 'BL', 'name' => 'SAINT BARTHELEMY', 'code' => '590'])->create();
        Country::factory(['short' => 'BM', 'name' => 'BERMUDA', 'code' => '1441'])->create();
        Country::factory(['short' => 'BN', 'name' => 'BRUNEI DARUSSALAM', 'code' => '673'])->create();
        Country::factory(['short' => 'BO', 'name' => 'BOLIVIA', 'code' => '591'])->create();
        Country::factory(['short' => 'BR', 'name' => 'BRAZIL', 'code' => '55'])->create();
        Country::factory(['short' => 'BS', 'name' => 'BAHAMAS', 'code' => '1242'])->create();
        Country::factory(['short' => 'BT', 'name' => 'BHUTAN', 'code' => '975'])->create();
        Country::factory(['short' => 'BW', 'name' => 'BOTSWANA', 'code' => '267'])->create();
        Country::factory(['short' => 'BY', 'name' => 'BELARUS', 'code' => '375'])->create();
        Country::factory(['short' => 'BZ', 'name' => 'BELIZE', 'code' => '501'])->create();
        Country::factory(['short' => 'CA', 'name' => 'CANADA', 'code' => '1'])->create();
        Country::factory(['short' => 'CC', 'name' => 'COCOS (KEELING) ISLANDS', 'code' => '61'])->create();
        Country::factory(['short' => 'CD', 'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'code' => '243'])->create();
        Country::factory(['short' => 'CF', 'name' => 'CENTRAL AFRICAN REPUBLIC', 'code' => '236'])->create();
        Country::factory(['short' => 'CG', 'name' => 'CONGO', 'code' => '242'])->create();
        Country::factory(['short' => 'CH', 'name' => 'SWITZERLAND', 'code' => '41'])->create();
        Country::factory(['short' => 'CI', 'name' => 'COTE D IVOIRE', 'code' => '225'])->create();
        Country::factory(['short' => 'CK', 'name' => 'COOK ISLANDS', 'code' => '682'])->create();
        Country::factory(['short' => 'CL', 'name' => 'CHILE', 'code' => '56'])->create();
        Country::factory(['short' => 'CM', 'name' => 'CAMEROON', 'code' => '237'])->create();
        Country::factory(['short' => 'CN', 'name' => 'CHINA', 'code' => '86'])->create();
        Country::factory(['short' => 'CO', 'name' => 'COLOMBIA', 'code' => '57'])->create();
        Country::factory(['short' => 'CR', 'name' => 'COSTA RICA', 'code' => '506'])->create();
        Country::factory(['short' => 'CU', 'name' => 'CUBA', 'code' => '53'])->create();
        Country::factory(['short' => 'CV', 'name' => 'CAPE VERDE', 'code' => '238'])->create();
        Country::factory(['short' => 'CX', 'name' => 'CHRISTMAS ISLAND', 'code' => '61'])->create();
        Country::factory(['short' => 'CY', 'name' => 'CYPRUS', 'code' => '357'])->create();
        Country::factory(['short' => 'CZ', 'name' => 'CZECH REPUBLIC', 'code' => '420'])->create();
        Country::factory(['short' => 'DE', 'name' => 'GERMANY', 'code' => '49'])->create();
        Country::factory(['short' => 'DJ', 'name' => 'DJIBOUTI', 'code' => '253'])->create();
        Country::factory(['short' => 'DK', 'name' => 'DENMARK', 'code' => '45'])->create();
        Country::factory(['short' => 'DM', 'name' => 'DOMINICA', 'code' => '1767'])->create();
        Country::factory(['short' => 'DO', 'name' => 'DOMINICAN REPUBLIC', 'code' => '1809'])->create();
        Country::factory(['short' => 'DZ', 'name' => 'ALGERIA', 'code' => '213'])->create();
        Country::factory(['short' => 'EC', 'name' => 'ECUADOR', 'code' => '593'])->create();
        Country::factory(['short' => 'EE', 'name' => 'ESTONIA', 'code' => '372'])->create();
        Country::factory(['short' => 'EG', 'name' => 'EGYPT', 'code' => '20'])->create();
        Country::factory(['short' => 'ER', 'name' => 'ERITREA', 'code' => '291'])->create();
        Country::factory(['short' => 'ES', 'name' => 'SPAIN', 'code' => '34'])->create();
        Country::factory(['short' => 'ET', 'name' => 'ETHIOPIA', 'code' => '251'])->create();
        Country::factory(['short' => 'FI', 'name' => 'FINLAND', 'code' => '358'])->create();
        Country::factory(['short' => 'FJ', 'name' => 'FIJI', 'code' => '679'])->create();
        Country::factory(['short' => 'FK', 'name' => 'FALKLAND ISLANDS (MALVINAS)', 'code' => '500'])->create();
        Country::factory(['short' => 'FM', 'name' => 'MICRONESIA, FEDERATED STATES OF', 'code' => '691'])->create();
        Country::factory(['short' => 'FO', 'name' => 'FAROE ISLANDS', 'code' => '298'])->create();
        Country::factory(['short' => 'FR', 'name' => 'FRANCE', 'code' => '33'])->create();
        Country::factory(['short' => 'GA', 'name' => 'GABON', 'code' => '241'])->create();
        Country::factory(['short' => 'GB', 'name' => 'UNITED KINGDOM', 'code' => '44'])->create();
        Country::factory(['short' => 'GD', 'name' => 'GRENADA', 'code' => '1473'])->create();
        Country::factory(['short' => 'GE', 'name' => 'GEORGIA', 'code' => '995'])->create();
        Country::factory(['short' => 'GH', 'name' => 'GHANA', 'code' => '233'])->create();
        Country::factory(['short' => 'GI', 'name' => 'GIBRALTAR', 'code' => '350'])->create();
        Country::factory(['short' => 'GL', 'name' => 'GREENLAND', 'code' => '299'])->create();
        Country::factory(['short' => 'GM', 'name' => 'GAMBIA', 'code' => '220'])->create();
        Country::factory(['short' => 'GN', 'name' => 'GUINEA', 'code' => '224'])->create();
        Country::factory(['short' => 'GQ', 'name' => 'EQUATORIAL GUINEA', 'code' => '240'])->create();
        Country::factory(['short' => 'GR', 'name' => 'GREECE', 'code' => '30'])->create();
        Country::factory(['short' => 'GT', 'name' => 'GUATEMALA', 'code' => '502'])->create();
        Country::factory(['short' => 'GU', 'name' => 'GUAM', 'code' => '1671'])->create();
        Country::factory(['short' => 'GW', 'name' => 'GUINEA-BISSAU', 'code' => '245'])->create();
        Country::factory(['short' => 'GY', 'name' => 'GUYANA', 'code' => '592'])->create();
        Country::factory(['short' => 'HK', 'name' => 'HONG KONG', 'code' => '852'])->create();
        Country::factory(['short' => 'HN', 'name' => 'HONDURAS', 'code' => '504'])->create();
        Country::factory(['short' => 'HR', 'name' => 'CROATIA', 'code' => '385'])->create();
        Country::factory(['short' => 'HT', 'name' => 'HAITI', 'code' => '509'])->create();
        Country::factory(['short' => 'HU', 'name' => 'HUNGARY', 'code' => '36'])->create();
        Country::factory(['short' => 'ID', 'name' => 'INDONESIA', 'code' => '62'])->create();
        Country::factory(['short' => 'IE', 'name' => 'IRELAND', 'code' => '353'])->create();
        Country::factory(['short' => 'IL', 'name' => 'ISRAEL', 'code' => '972'])->create();
        Country::factory(['short' => 'IM', 'name' => 'ISLE OF MAN', 'code' => '44'])->create();
        Country::factory(['short' => 'IN', 'name' => 'INDIA', 'code' => '91'])->create();
        Country::factory(['short' => 'IQ', 'name' => 'IRAQ', 'code' => '964'])->create();
        Country::factory(['short' => 'IR', 'name' => 'IRAN, ISLAMIC REPUBLIC OF', 'code' => '98'])->create();
        Country::factory(['short' => 'IS', 'name' => 'ICELAND', 'code' => '354'])->create();
        Country::factory(['short' => 'IT', 'name' => 'ITALY', 'code' => '39'])->create();
        Country::factory(['short' => 'JM', 'name' => 'JAMAICA', 'code' => '1876'])->create();
        Country::factory(['short' => 'JO', 'name' => 'JORDAN', 'code' => '962'])->create();
        Country::factory(['short' => 'JP', 'name' => 'JAPAN', 'code' => '81'])->create();
        Country::factory(['short' => 'KE', 'name' => 'KENYA', 'code' => '254'])->create();
        Country::factory(['short' => 'KG', 'name' => 'KYRGYZSTAN', 'code' => '996'])->create();
        Country::factory(['short' => 'KH', 'name' => 'CAMBODIA', 'code' => '855'])->create();
        Country::factory(['short' => 'KI', 'name' => 'KIRIBATI', 'code' => '686'])->create();
        Country::factory(['short' => 'KM', 'name' => 'COMOROS', 'code' => '269'])->create();
        Country::factory(['short' => 'KN', 'name' => 'SAINT KITTS AND NEVIS', 'code' => '1869'])->create();
        Country::factory(['short' => 'KP', 'name' => 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF', 'code' => '850'])->create();
        Country::factory(['short' => 'KR', 'name' => 'KOREA REPUBLIC OF', 'code' => '82'])->create();
        Country::factory(['short' => 'KW', 'name' => 'KUWAIT', 'code' => '965'])->create();
        Country::factory(['short' => 'KY', 'name' => 'CAYMAN ISLANDS', 'code' => '1345'])->create();
        Country::factory(['short' => 'KZ', 'name' => 'KAZAKSTAN', 'code' => '7'])->create();
        Country::factory(['short' => 'LA', 'name' => 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'code' => '856'])->create();
        Country::factory(['short' => 'LB', 'name' => 'LEBANON', 'code' => '961'])->create();
        Country::factory(['short' => 'LC', 'name' => 'SAINT LUCIA', 'code' => '1758'])->create();
        Country::factory(['short' => 'LI', 'name' => 'LIECHTENSTEIN', 'code' => '423'])->create();
        Country::factory(['short' => 'LK', 'name' => 'SRI LANKA', 'code' => '94'])->create();
        Country::factory(['short' => 'LR', 'name' => 'LIBERIA', 'code' => '231'])->create();
        Country::factory(['short' => 'LS', 'name' => 'LESOTHO', 'code' => '266'])->create();
        Country::factory(['short' => 'LT', 'name' => 'LITHUANIA', 'code' => '370'])->create();
        Country::factory(['short' => 'LU', 'name' => 'LUXEMBOURG', 'code' => '352'])->create();
        Country::factory(['short' => 'LV', 'name' => 'LATVIA', 'code' => '371'])->create();
        Country::factory(['short' => 'LY', 'name' => 'LIBYAN ARAB JAMAHIRIYA', 'code' => '218'])->create();
        Country::factory(['short' => 'MA', 'name' => 'MOROCCO', 'code' => '212'])->create();
        Country::factory(['short' => 'MC', 'name' => 'MONACO', 'code' => '377'])->create();
        Country::factory(['short' => 'MD', 'name' => 'MOLDOVA, REPUBLIC OF', 'code' => '373'])->create();
        Country::factory(['short' => 'ME', 'name' => 'MONTENEGRO', 'code' => '382'])->create();
        Country::factory(['short' => 'MF', 'name' => 'SAINT MARTIN', 'code' => '1599'])->create();
        Country::factory(['short' => 'MG', 'name' => 'MADAGASCAR', 'code' => '261'])->create();
        Country::factory(['short' => 'MH', 'name' => 'MARSHALL ISLANDS', 'code' => '692'])->create();
        Country::factory(['short' => 'MK', 'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'code' => '389'])->create();
        Country::factory(['short' => 'ML', 'name' => 'MALI', 'code' => '223'])->create();
        Country::factory(['short' => 'MM', 'name' => 'MYANMAR', 'code' => '95'])->create();
        Country::factory(['short' => 'MN', 'name' => 'MONGOLIA', 'code' => '976'])->create();
        Country::factory(['short' => 'MO', 'name' => 'MACAU', 'code' => '853'])->create();
        Country::factory(['short' => 'MP', 'name' => 'NORTHERN MARIANA ISLANDS', 'code' => '1670'])->create();
        Country::factory(['short' => 'MR', 'name' => 'MAURITANIA', 'code' => '222'])->create();
        Country::factory(['short' => 'MS', 'name' => 'MONTSERRAT', 'code' => '1664'])->create();
        Country::factory(['short' => 'MT', 'name' => 'MALTA', 'code' => '356'])->create();
        Country::factory(['short' => 'MU', 'name' => 'MAURITIUS', 'code' => '230'])->create();
        Country::factory(['short' => 'MV', 'name' => 'MALDIVES', 'code' => '960'])->create();
        Country::factory(['short' => 'MW', 'name' => 'MALAWI', 'code' => '265'])->create();
        Country::factory(['short' => 'MX', 'name' => 'MEXICO', 'code' => '52'])->create();
        Country::factory(['short' => 'MY', 'name' => 'MALAYSIA', 'code' => '60'])->create();
        Country::factory(['short' => 'MZ', 'name' => 'MOZAMBIQUE', 'code' => '258'])->create();
        Country::factory(['short' => 'NA', 'name' => 'NAMIBIA', 'code' => '264'])->create();
        Country::factory(['short' => 'NC', 'name' => 'NEW CALEDONIA', 'code' => '687'])->create();
        Country::factory(['short' => 'NE', 'name' => 'NIGER', 'code' => '227'])->create();
        Country::factory(['short' => 'NG', 'name' => 'NIGERIA', 'code' => '234'])->create();
        Country::factory(['short' => 'NI', 'name' => 'NICARAGUA', 'code' => '505'])->create();
        Country::factory(['short' => 'NL', 'name' => 'NETHERLANDS', 'code' => '31'])->create();
        Country::factory(['short' => 'NO', 'name' => 'NORWAY', 'code' => '47'])->create();
        Country::factory(['short' => 'NP', 'name' => 'NEPAL', 'code' => '977'])->create();
        Country::factory(['short' => 'NR', 'name' => 'NAURU', 'code' => '674'])->create();
        Country::factory(['short' => 'NU', 'name' => 'NIUE', 'code' => '683'])->create();
        Country::factory(['short' => 'NZ', 'name' => 'NEW ZEALAND', 'code' => '64'])->create();
        Country::factory(['short' => 'OM', 'name' => 'OMAN', 'code' => '968'])->create();
        Country::factory(['short' => 'PA', 'name' => 'PANAMA', 'code' => '507'])->create();
        Country::factory(['short' => 'PE', 'name' => 'PERU', 'code' => '51'])->create();
        Country::factory(['short' => 'PF', 'name' => 'FRENCH POLYNESIA', 'code' => '689'])->create();
        Country::factory(['short' => 'PG', 'name' => 'PAPUA NEW GUINEA', 'code' => '675'])->create();
        Country::factory(['short' => 'PH', 'name' => 'PHILIPPINES', 'code' => '63'])->create();
        Country::factory(['short' => 'PK', 'name' => 'PAKISTAN', 'code' => '92'])->create();
        Country::factory(['short' => 'PL', 'name' => 'POLAND', 'code' => '48'])->create();
        Country::factory(['short' => 'PM', 'name' => 'SAINT PIERRE AND MIQUELON', 'code' => '508'])->create();
        Country::factory(['short' => 'PN', 'name' => 'PITCAIRN', 'code' => '870'])->create();
        Country::factory(['short' => 'PR', 'name' => 'PUERTO RICO', 'code' => '1'])->create();
        Country::factory(['short' => 'PT', 'name' => 'PORTUGAL', 'code' => '351'])->create();
        Country::factory(['short' => 'PW', 'name' => 'PALAU', 'code' => '680'])->create();
        Country::factory(['short' => 'PY', 'name' => 'PARAGUAY', 'code' => '595'])->create();
        Country::factory(['short' => 'QA', 'name' => 'QATAR', 'code' => '974'])->create();
        Country::factory(['short' => 'RO', 'name' => 'ROMANIA', 'code' => '40'])->create();
        Country::factory(['short' => 'RS', 'name' => 'SERBIA', 'code' => '381'])->create();
        Country::factory(['short' => 'RU', 'name' => 'RUSSIAN FEDERATION', 'code' => '7'])->create();
        Country::factory(['short' => 'RW', 'name' => 'RWANDA', 'code' => '250'])->create();
        Country::factory(['short' => 'SA', 'name' => 'SAUDI ARABIA', 'code' => '966'])->create();
        Country::factory(['short' => 'SB', 'name' => 'SOLOMON ISLANDS', 'code' => '677'])->create();
        Country::factory(['short' => 'SC', 'name' => 'SEYCHELLES', 'code' => '248'])->create();
        Country::factory(['short' => 'SD', 'name' => 'SUDAN', 'code' => '249'])->create();
        Country::factory(['short' => 'SE', 'name' => 'SWEDEN', 'code' => '46'])->create();
        Country::factory(['short' => 'SG', 'name' => 'SINGAPORE', 'code' => '65'])->create();
        Country::factory(['short' => 'SH', 'name' => 'SAINT HELENA', 'code' => '290'])->create();
        Country::factory(['short' => 'SI', 'name' => 'SLOVENIA', 'code' => '386'])->create();
        Country::factory(['short' => 'SK', 'name' => 'SLOVAKIA', 'code' => '421'])->create();
        Country::factory(['short' => 'SL', 'name' => 'SIERRA LEONE', 'code' => '232'])->create();
        Country::factory(['short' => 'SM', 'name' => 'SAN MARINO', 'code' => '378'])->create();
        Country::factory(['short' => 'SN', 'name' => 'SENEGAL', 'code' => '221'])->create();
        Country::factory(['short' => 'SO', 'name' => 'SOMALIA', 'code' => '252'])->create();
        Country::factory(['short' => 'SR', 'name' => 'SURINAME', 'code' => '597'])->create();
        Country::factory(['short' => 'ST', 'name' => 'SAO TOME AND PRINCIPE', 'code' => '239'])->create();
        Country::factory(['short' => 'SV', 'name' => 'EL SALVADOR', 'code' => '503'])->create();
        Country::factory(['short' => 'SY', 'name' => 'SYRIAN ARAB REPUBLIC', 'code' => '963'])->create();
        Country::factory(['short' => 'SZ', 'name' => 'SWAZILAND', 'code' => '268'])->create();
        Country::factory(['short' => 'TC', 'name' => 'TURKS AND CAICOS ISLANDS', 'code' => '1649'])->create();
        Country::factory(['short' => 'TD', 'name' => 'CHAD', 'code' => '235'])->create();
        Country::factory(['short' => 'TG', 'name' => 'TOGO', 'code' => '228'])->create();
        Country::factory(['short' => 'TH', 'name' => 'THAILAND', 'code' => '66'])->create();
        Country::factory(['short' => 'TJ', 'name' => 'TAJIKISTAN', 'code' => '992'])->create();
        Country::factory(['short' => 'TK', 'name' => 'TOKELAU', 'code' => '690'])->create();
        Country::factory(['short' => 'TL', 'name' => 'TIMOR-LESTE', 'code' => '670'])->create();
        Country::factory(['short' => 'TM', 'name' => 'TURKMENISTAN', 'code' => '993'])->create();
        Country::factory(['short' => 'TN', 'name' => 'TUNISIA', 'code' => '216'])->create();
        Country::factory(['short' => 'TO', 'name' => 'TONGA', 'code' => '676'])->create();
        Country::factory(['short' => 'TR', 'name' => 'TURKEY', 'code' => '90'])->create();
        Country::factory(['short' => 'TT', 'name' => 'TRINIDAD AND TOBAGO', 'code' => '1868'])->create();
        Country::factory(['short' => 'TV', 'name' => 'TUVALU', 'code' => '688'])->create();
        Country::factory(['short' => 'TW', 'name' => 'TAIWAN, PROVINCE OF CHINA', 'code' => '886'])->create();
        Country::factory(['short' => 'TZ', 'name' => 'TANZANIA, UNITED REPUBLIC OF', 'code' => '255'])->create();
        Country::factory(['short' => 'UA', 'name' => 'UKRAINE', 'code' => '380'])->create();
        Country::factory(['short' => 'UG', 'name' => 'UGANDA', 'code' => '256'])->create();
        Country::factory(['short' => 'US', 'name' => 'UNITED STATES', 'code' => '1'])->create();
        Country::factory(['short' => 'UY', 'name' => 'URUGUAY', 'code' => '598'])->create();
        Country::factory(['short' => 'UZ', 'name' => 'UZBEKISTAN', 'code' => '998'])->create();
        Country::factory(['short' => 'VA', 'name' => 'HOLY SEE (VATICAN CITY STATE)', 'code' => '39'])->create();
        Country::factory(['short' => 'VC', 'name' => 'SAINT VINCENT AND THE GRENADINES', 'code' => '1784'])->create();
        Country::factory(['short' => 'VE', 'name' => 'VENEZUELA', 'code' => '58'])->create();
        Country::factory(['short' => 'VG', 'name' => 'VIRGIN ISLANDS, BRITISH', 'code' => '1284'])->create();
        Country::factory(['short' => 'VI', 'name' => 'VIRGIN ISLANDS, U.S.', 'code' => '1340'])->create();
        Country::factory(['short' => 'VN', 'name' => 'VIET NAM', 'code' => '84'])->create();
        Country::factory(['short' => 'VU', 'name' => 'VANUATU', 'code' => '678'])->create();
        Country::factory(['short' => 'WF', 'name' => 'WALLIS AND FUTUNA', 'code' => '681'])->create();
        Country::factory(['short' => 'WS', 'name' => 'SAMOA', 'code' => '685'])->create();
        Country::factory(['short' => 'XK', 'name' => 'KOSOVO', 'code' => '381'])->create();
        Country::factory(['short' => 'YE', 'name' => 'YEMEN', 'code' => '967'])->create();
        Country::factory(['short' => 'YT', 'name' => 'MAYOTTE', 'code' => '262'])->create();
        Country::factory(['short' => 'ZA', 'name' => 'SOUTH AFRICA', 'code' => '27'])->create();
        Country::factory(['short' => 'ZM', 'name' => 'ZAMBIA', 'code' => '260'])->create();
        Country::factory(['short' => 'ZW', 'name' => 'ZIMBABWE', 'code' => '263'])->create();
    }
}
