<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Language::factory()->create(['code' => 'ab', 'name' => 'Abkhazian']);
        Language::factory()->create(['code' => 'aa', 'name' => 'Afar']);
        Language::factory()->create(['code' => 'af', 'name' => 'Afrikaans']);
        Language::factory()->create(['code' => 'ak', 'name' => 'Akan']);
        Language::factory()->create(['code' => 'sq', 'name' => 'Albanian']);
        Language::factory()->create(['code' => 'am', 'name' => 'Amharic']);
        Language::factory()->create(['code' => 'ar', 'name' => 'Arabic']);
        Language::factory()->create(['code' => 'an', 'name' => 'Aragonese']);
        Language::factory()->create(['code' => 'hy', 'name' => 'Armenian']);
        Language::factory()->create(['code' => 'as', 'name' => 'Assamese']);
        Language::factory()->create(['code' => 'av', 'name' => 'Avaric']);
        Language::factory()->create(['code' => 'ae', 'name' => 'Avestan']);
        Language::factory()->create(['code' => 'ay', 'name' => 'Aymara']);
        Language::factory()->create(['code' => 'az', 'name' => 'Azerbaijani']);
        Language::factory()->create(['code' => 'bm', 'name' => 'Bambara']);
        Language::factory()->create(['code' => 'ba', 'name' => 'Bashkir']);
        Language::factory()->create(['code' => 'eu', 'name' => 'Basque']);
        Language::factory()->create(['code' => 'be', 'name' => 'Belarusian']);
        Language::factory()->create(['code' => 'bn', 'name' => 'Bengali']);
        Language::factory()->create(['code' => 'bh', 'name' => 'Bihari languages']);
        Language::factory()->create(['code' => 'bi', 'name' => 'Bislama']);
        Language::factory()->create(['code' => 'bs', 'name' => 'Bosnian']);
        Language::factory()->create(['code' => 'br', 'name' => 'Breton']);
        Language::factory()->create(['code' => 'bg', 'name' => 'Bulgarian']);
        Language::factory()->create(['code' => 'my', 'name' => 'Burmese']);
        Language::factory()->create(['code' => 'ca', 'name' => 'Catalan, Valcodeian']);
        Language::factory()->create(['code' => 'km', 'name' => 'Central Khmer']);
        Language::factory()->create(['code' => 'ch', 'name' => 'Chamorro']);
        Language::factory()->create(['code' => 'ce', 'name' => 'Chechen']);
        Language::factory()->create(['code' => 'ny', 'name' => 'Chichewa, Chewa, Nyanja']);
        Language::factory()->create(['code' => 'zh', 'name' => 'Chinese']);
        Language::factory()->create(['code' => 'cu', 'name' => 'Church Slavonic, Old Bulgarian, Old Church Slavonic']);
        Language::factory()->create(['code' => 'cv', 'name' => 'Chuvash']);
        Language::factory()->create(['code' => 'kw', 'name' => 'Cornish']);
        Language::factory()->create(['code' => 'co', 'name' => 'Corsican']);
        Language::factory()->create(['code' => 'cr', 'name' => 'Cree']);
        Language::factory()->create(['code' => 'hr', 'name' => 'Croatian']);
        Language::factory()->create(['code' => 'cs', 'name' => 'Czech']);
        Language::factory()->create(['code' => 'da', 'name' => 'Danish']);
        Language::factory()->create(['code' => 'dv', 'name' => 'Divehi, Dhivehi, Maldivian']);
        Language::factory()->create(['code' => 'nl', 'name' => 'Dutch, Flemish']);
        Language::factory()->create(['code' => 'dz', 'name' => 'Dzongkha']);
        Language::factory()->create(['code' => 'en', 'name' => 'English']);
        Language::factory()->create(['code' => 'eo', 'name' => 'Esperanto']);
        Language::factory()->create(['code' => 'et', 'name' => 'Estonian']);
        Language::factory()->create(['code' => 'ee', 'name' => 'Ewe']);
        Language::factory()->create(['code' => 'fr', 'name' => 'French']);
        Language::factory()->create(['code' => 'fo', 'name' => 'Faroese']);
        Language::factory()->create(['code' => 'fj', 'name' => 'Fijian']);
        Language::factory()->create(['code' => 'fi', 'name' => 'Finnish']);
        Language::factory()->create(['code' => 'fr', 'name' => 'Frcodeh']);
        Language::factory()->create(['code' => 'ff', 'name' => 'Fulah']);
        Language::factory()->create(['code' => 'gd', 'name' => 'Gaelic, Scottish Gaelic']);
        Language::factory()->create(['code' => 'gl', 'name' => 'Galician']);
        Language::factory()->create(['code' => 'lg', 'name' => 'Ganda']);
        Language::factory()->create(['code' => 'ka', 'name' => 'Georgian']);
        Language::factory()->create(['code' => 'de', 'name' => 'German']);
        Language::factory()->create(['code' => 'ki', 'name' => 'Gikuyu, Kikuyu']);
        Language::factory()->create(['code' => 'el', 'name' => 'Greek (Modern)']);
        Language::factory()->create(['code' => 'kl', 'name' => 'Greenlandic, Kalaallisut']);
        Language::factory()->create(['code' => 'gn', 'name' => 'Guarani']);
        Language::factory()->create(['code' => 'gu', 'name' => 'Gujarati']);
        Language::factory()->create(['code' => 'ht', 'name' => 'Haitian, Haitian Creole']);
        Language::factory()->create(['code' => 'ha', 'name' => 'Hausa']);
        Language::factory()->create(['code' => 'he', 'name' => 'Hebrew']);
        Language::factory()->create(['code' => 'hz', 'name' => 'Herero']);
        Language::factory()->create(['code' => 'hi', 'name' => 'Hindi']);
        Language::factory()->create(['code' => 'ho', 'name' => 'Hiri Motu']);
        Language::factory()->create(['code' => 'hu', 'name' => 'Hungarian']);
        Language::factory()->create(['code' => 'is', 'name' => 'Icelandic']);
        Language::factory()->create(['code' => 'io', 'name' => 'Ido']);
        Language::factory()->create(['code' => 'ig', 'name' => 'Igbo']);
        Language::factory()->create(['code' => 'id', 'name' => 'Indonesian']);
        Language::factory()->create(['code' => 'ia', 'name' => 'Interlingua (International Auxiliary Language Association)']);
        Language::factory()->create(['code' => 'ie', 'name' => 'Interlingue']);
        Language::factory()->create(['code' => 'iu', 'name' => 'Inuktitut']);
        Language::factory()->create(['code' => 'ik', 'name' => 'Inupiaq']);
        Language::factory()->create(['code' => 'ga', 'name' => 'Irish']);
        Language::factory()->create(['code' => 'it', 'name' => 'Italian']);
        Language::factory()->create(['code' => 'ja', 'name' => 'Japanese']);
        Language::factory()->create(['code' => 'jv', 'name' => 'Javanese']);
        Language::factory()->create(['code' => 'kn', 'name' => 'Kannada']);
        Language::factory()->create(['code' => 'kr', 'name' => 'Kanuri']);
        Language::factory()->create(['code' => 'ks', 'name' => 'Kashmiri']);
        Language::factory()->create(['code' => 'kk', 'name' => 'Kazakh']);
        Language::factory()->create(['code' => 'rw', 'name' => 'Kinyarwanda']);
        Language::factory()->create(['code' => 'kv', 'name' => 'Komi']);
        Language::factory()->create(['code' => 'kg', 'name' => 'Kongo']);
        Language::factory()->create(['code' => 'ko', 'name' => 'Korean']);
        Language::factory()->create(['code' => 'kj', 'name' => 'Kwanyama, Kuanyama']);
        Language::factory()->create(['code' => 'ku', 'name' => 'Kurdish']);
        Language::factory()->create(['code' => 'ky', 'name' => 'Kyrgyz']);
        Language::factory()->create(['code' => 'lo', 'name' => 'Lao']);
        Language::factory()->create(['code' => 'la', 'name' => 'Latin']);
        Language::factory()->create(['code' => 'lv', 'name' => 'Latvian']);
        Language::factory()->create(['code' => 'lb', 'name' => 'Letzeburgesch, Luxembourgish']);
        Language::factory()->create(['code' => 'li', 'name' => 'Limburgish, Limburgan, Limburger']);
        Language::factory()->create(['code' => 'ln', 'name' => 'Lingala']);
        Language::factory()->create(['code' => 'lt', 'name' => 'Lithuanian']);
        Language::factory()->create(['code' => 'lu', 'name' => 'Luba-Katanga']);
        Language::factory()->create(['code' => 'mk', 'name' => 'Macedonian']);
        Language::factory()->create(['code' => 'mg', 'name' => 'Malagasy']);
        Language::factory()->create(['code' => 'ms', 'name' => 'Malay']);
        Language::factory()->create(['code' => 'ml', 'name' => 'Malayalam']);
        Language::factory()->create(['code' => 'mt', 'name' => 'Maltese']);
        Language::factory()->create(['code' => 'gv', 'name' => 'Manx']);
        Language::factory()->create(['code' => 'mi', 'name' => 'Maori']);
        Language::factory()->create(['code' => 'mr', 'name' => 'Marathi']);
        Language::factory()->create(['code' => 'mh', 'name' => 'Marshallese']);
        Language::factory()->create(['code' => 'ro', 'name' => 'Moldovan, Moldavian, Romanian']);
        Language::factory()->create(['code' => 'mn', 'name' => 'Mongolian']);
        Language::factory()->create(['code' => 'na', 'name' => 'Nauru']);
        Language::factory()->create(['code' => 'nv', 'name' => 'Navajo, Navaho']);
        Language::factory()->create(['code' => 'nd', 'name' => 'Northern Ndebele']);
        Language::factory()->create(['code' => 'ng', 'name' => 'Ndonga']);
        Language::factory()->create(['code' => 'ne', 'name' => 'Nepali']);
        Language::factory()->create(['code' => 'se', 'name' => 'Northern Sami']);
        Language::factory()->create(['code' => 'no', 'name' => 'Norwegian']);
        Language::factory()->create(['code' => 'nb', 'name' => 'Norwegian Bokmål']);
        Language::factory()->create(['code' => 'nn', 'name' => 'Norwegian Nynorsk']);
        Language::factory()->create(['code' => 'ii', 'name' => 'Nuosu, Sichuan Yi']);
        Language::factory()->create(['code' => 'oc', 'name' => 'Occitan (post 1500)']);
        Language::factory()->create(['code' => 'oj', 'name' => 'Ojibwa']);
        Language::factory()->create(['code' => 'or', 'name' => 'Oriya']);
        Language::factory()->create(['code' => 'om', 'name' => 'Oromo']);
        Language::factory()->create(['code' => 'os', 'name' => 'Ossetian, Ossetic']);
        Language::factory()->create(['code' => 'pi', 'name' => 'Pali']);
        Language::factory()->create(['code' => 'pa', 'name' => 'Panjabi, Punjabi']);
        Language::factory()->create(['code' => 'ps', 'name' => 'Pashto, Pushto']);
        Language::factory()->create(['code' => 'fa', 'name' => 'Persian']);
        Language::factory()->create(['code' => 'pl', 'name' => 'Polish']);
        Language::factory()->create(['code' => 'pt', 'name' => 'Portuguese']);
        Language::factory()->create(['code' => 'qu', 'name' => 'Quechua']);
        Language::factory()->create(['code' => 'rm', 'name' => 'Romansh']);
        Language::factory()->create(['code' => 'rn', 'name' => 'Rundi']);
        Language::factory()->create(['code' => 'ru', 'name' => 'Russian']);
        Language::factory()->create(['code' => 'sm', 'name' => 'Samoan']);
        Language::factory()->create(['code' => 'sg', 'name' => 'Sango']);
        Language::factory()->create(['code' => 'sa', 'name' => 'Sanskrit']);
        Language::factory()->create(['code' => 'sc', 'name' => 'Sardinian']);
        Language::factory()->create(['code' => 'sr', 'name' => 'Serbian']);
        Language::factory()->create(['code' => 'sn', 'name' => 'Shona']);
        Language::factory()->create(['code' => 'sd', 'name' => 'Sindhi']);
        Language::factory()->create(['code' => 'si', 'name' => 'Sinhala, Sinhalese']);
        Language::factory()->create(['code' => 'sk', 'name' => 'Slovak']);
        Language::factory()->create(['code' => 'sl', 'name' => 'Slovenian']);
        Language::factory()->create(['code' => 'so', 'name' => 'Somali']);
        Language::factory()->create(['code' => 'st', 'name' => 'Sotho, Southern']);
        Language::factory()->create(['code' => 'nr', 'name' => 'South Ndebele']);
        Language::factory()->create(['code' => 'es', 'name' => 'Spanish']);
        Language::factory()->create(['code' => 'su', 'name' => 'Sundanese']);
        Language::factory()->create(['code' => 'sw', 'name' => 'Swahili']);
        Language::factory()->create(['code' => 'ss', 'name' => 'Swati']);
        Language::factory()->create(['code' => 'sv', 'name' => 'Swedish']);
        Language::factory()->create(['code' => 'tl', 'name' => 'Tagalog']);
        Language::factory()->create(['code' => 'ty', 'name' => 'Tahitian']);
        Language::factory()->create(['code' => 'tg', 'name' => 'Tajik']);
        Language::factory()->create(['code' => 'ta', 'name' => 'Tamil']);
        Language::factory()->create(['code' => 'tt', 'name' => 'Tatar']);
        Language::factory()->create(['code' => 'te', 'name' => 'Telugu']);
        Language::factory()->create(['code' => 'th', 'name' => 'Thai']);
        Language::factory()->create(['code' => 'bo', 'name' => 'Tibetan']);
        Language::factory()->create(['code' => 'ti', 'name' => 'Tigrinya']);
        Language::factory()->create(['code' => 'to', 'name' => 'Tonga (Tonga Islands)']);
        Language::factory()->create(['code' => 'ts', 'name' => 'Tsonga']);
        Language::factory()->create(['code' => 'tn', 'name' => 'Tswana']);
        Language::factory()->create(['code' => 'tr', 'name' => 'Turkish']);
        Language::factory()->create(['code' => 'tk', 'name' => 'Turkmen']);
        Language::factory()->create(['code' => 'tw', 'name' => 'Twi']);
        Language::factory()->create(['code' => 'ug', 'name' => 'Uighur, Uyghur']);
        Language::factory()->create(['code' => 'uk', 'name' => 'Ukrainian']);
        Language::factory()->create(['code' => 'ur', 'name' => 'Urdu']);
        Language::factory()->create(['code' => 'uz', 'name' => 'Uzbek']);
        Language::factory()->create(['code' => 've', 'name' => 'Venda']);
        Language::factory()->create(['code' => 'vi', 'name' => 'Vietnamese']);
        Language::factory()->create(['code' => 'vo', 'name' => 'Volap_k']);
        Language::factory()->create(['code' => 'wa', 'name' => 'Walloon']);
        Language::factory()->create(['code' => 'cy', 'name' => 'Welsh']);
        Language::factory()->create(['code' => 'fy', 'name' => 'Western Frisian']);
        Language::factory()->create(['code' => 'wo', 'name' => 'Wolof']);
        Language::factory()->create(['code' => 'xh', 'name' => 'Xhosa']);
        Language::factory()->create(['code' => 'yi', 'name' => 'Yiddish']);
        Language::factory()->create(['code' => 'yo', 'name' => 'Yoruba']);
        Language::factory()->create(['code' => 'za', 'name' => 'Zhuang, Chuang']);
        Language::factory()->create(['code' => 'zu', 'name' => 'Zulu']);
    }
}
